<?php

namespace Database\Seeders;

use App\Models\MedicalPackage;
use Illuminate\Database\Seeder;

class MedicalPackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $packages = [
            [
                'name' => 'Aarogyam Monsoon Basic Package',
                'slug' => 'aarogyam-monsoon-basic-package',
                'category' => 'full_body',
                'category_label' => 'Full Body Health',
                'badge' => 'Bestseller',
                'test_count' => 68,
                'short_description' => 'Comprehensive seasonal health screening designed to protect immunity, detect organ stress, and evaluate vital parameters at an unbeatable value.',
                'parameters' => [
                    'Complete Blood Count (CBC) - 28 Parameters',
                    'Liver Function Extended (LFT) - 12 Parameters',
                    'Kidney Function Advanced (KFT) - 7 Parameters',
                    'Lipid Profile Advanced (Heart Health) - 10 Parameters',
                    'Ultrasensitive TSH (Thyroid) - 1 Parameter',
                    'Vitamin Profile (D3 & B12) - 2 Parameters',
                    'Diabetes Profile (FBS & Average Sugar) - 2 Parameters',
                    'Iron Deficiency Profile - 4 Parameters',
                    'Electrolytes (Sodium & Potassium) - 2 Parameters',
                ],
                'original_price' => 2199.00,
                'discounted_price' => 999.00,
                'discount_percent' => 55,
                'fasting_required' => true,
                'sample_type' => 'Blood & Urine',
                'report_time' => 'Same Day (Within 8-12 hrs)',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Aarogyam Winter Basic with UTSH',
                'slug' => 'aarogyam-winter-basic-with-utsh',
                'category' => 'full_body',
                'category_label' => 'Full Body Health',
                'badge' => 'Popular',
                'test_count' => 68,
                'short_description' => 'Seasonal wellness panel with ultrasensitive thyroid screening, metabolic markers, and full blood counts for complete peace of mind.',
                'parameters' => [
                    'Ultrasensitive TSH (UTSH) - High Precision',
                    'Complete Hemogram Panel - 28 Parameters',
                    'Liver Function Extended - 12 Parameters',
                    'Renal Function Profile - 7 Parameters',
                    'Lipid Profile (Cholesterol & Triglycerides) - 10 Parameters',
                    'Diabetic Screening (Glucose & HbA1c est) - 2 Parameters',
                    'Serum Calcium & Phosphorous - 2 Parameters',
                    'Iron & TIBC Profile - 3 Parameters',
                ],
                'original_price' => 2499.00,
                'discounted_price' => 1199.00,
                'discount_percent' => 52,
                'fasting_required' => true,
                'sample_type' => 'Blood & Urine',
                'report_time' => 'Same Day (Within 8-12 hrs)',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Full Body Checkup Guwahati Special',
                'slug' => 'full-body-checkup-guwahati-price-1699',
                'category' => 'full_body',
                'category_label' => 'Full Body Health',
                'badge' => 'Top Pick in Guwahati',
                'test_count' => 82,
                'short_description' => 'Our flagship city package tailored for residents of Guwahati and Assam. Covers every vital organ system with free doorstep collection.',
                'parameters' => [
                    'Hemogram Panel - 6 Part DIFF (CBC - 28 Parameters)',
                    'Liver Extended Panel (Bilirubin, SGOT, SGPT, ALP, Protein - 12)',
                    'Kidney Function & Electrolytes (Urea, Creatinine, Uric Acid, BUN - 7)',
                    'Lipid Profile Advanced (Total, HDL, LDL, VLDL, Triglycerides - 10)',
                    'Thyroid Trio (T3, T4, TSH) - 3 Parameters',
                    'HbA1c & Fasting Blood Sugar (FBS) - 2 Parameters',
                    'Vitamin D3 (25-OH) & Vitamin B12 - 2 Parameters',
                    'Complete Urine Routine Analysis - 18 Parameters',
                ],
                'original_price' => 3500.00,
                'discounted_price' => 1699.00,
                'discount_percent' => 51,
                'fasting_required' => true,
                'sample_type' => 'Blood & Urine',
                'report_time' => 'Same Day (Within 8-12 hrs)',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Aarogyam C Plus Profile with UTSH',
                'slug' => 'aarogyam-c-plus-profile-with-utsh',
                'category' => 'full_body',
                'category_label' => 'Full Body Health',
                'badge' => 'Comprehensive',
                'test_count' => 80,
                'short_description' => 'Targeted preventive checkup highlighting cardiac biomarkers, hormone balance, extended liver & renal screening, and blood indices.',
                'parameters' => [
                    'Cardiac Risk Screen (Apolipoproteins & Lipids - 10)',
                    'Ultrasensitive TSH (UTSH) - 1 Parameter',
                    'Liver Extended Panel - 12 Parameters',
                    'Renal Function Profile (KIDPRO) - 7 Parameters',
                    'Hemogram 6-Part DIFF - 28 Parameters',
                    'Iron Deficiency & Ferritin - 4 Parameters',
                    'Serum Electrolytes (Na, K, Cl) - 3 Parameters',
                    'Urine Microalbumin & Routine - 15 Parameters',
                ],
                'original_price' => 3800.00,
                'discounted_price' => 1799.00,
                'discount_percent' => 53,
                'fasting_required' => true,
                'sample_type' => 'Blood & Urine',
                'report_time' => 'Same Day (Within 10-12 hrs)',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Aarogyam C Pro Package',
                'slug' => 'aarogyam-c-pro-package',
                'category' => 'full_body',
                'category_label' => 'Executive Health',
                'badge' => 'Executive',
                'test_count' => 95,
                'short_description' => 'Make a wise investment today, avoid forced expenditure tomorrow. Advanced metabolic screening, cardiac markers, and hormonal mapping.',
                'parameters' => [
                    'Complete Blood Count CBC - 28 Parameters',
                    'Comprehensive Liver Profile LFT - 12 Parameters',
                    'Kidney Profile with GFR Calculation - 8 Parameters',
                    'Extended Lipid Profile with Apo-A1 & Apo-B - 12 Parameters',
                    'Complete Thyroid Panel (FT3, FT4, UTSH) - 3 Parameters',
                    'Diabetes Panel (HbA1c + Fasting Sugar) - 2 Parameters',
                    'Vitamin D3, B12 & Folic Acid - 3 Parameters',
                    'High Sensitivity C-Reactive Protein (hs-CRP) - 1 Parameter',
                    'Pancreatic Enzymes (Amylase, Lipase) - 2 Parameters',
                    'Complete Urine Chemistry - 24 Parameters',
                ],
                'original_price' => 4999.00,
                'discounted_price' => 2499.00,
                'discount_percent' => 50,
                'fasting_required' => true,
                'sample_type' => 'Blood & Urine',
                'report_time' => 'Within 24 Hours',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Aarogyam E Plus Executive Package',
                'slug' => 'aarogyam-e-plus-package',
                'category' => 'full_body',
                'category_label' => 'Master Health Checkup',
                'badge' => 'Master Checkup',
                'test_count' => 110,
                'short_description' => 'Live Healthy, Stay Fit. The most complete diagnostic protocol available in Northeast India covering toxic metals, cardiac risk, cancer screening markers, and hormones.',
                'parameters' => [
                    'Toxic & Heavy Metals Screen (Lead, Arsenic, Mercury, Cadmium) - 6',
                    'Cardiac Biomarkers (hs-CRP, Homocysteine, Apo-A1, Apo-B) - 4',
                    'Full Thyroid Spectrum (Free T3, Free T4, UTSH, Anti-TPO) - 4',
                    'Comprehensive Diabetic Workup (HbA1c, Average Glucose, Insulin) - 3',
                    'Complete Vitamin & Mineral Panel (D3, B12, Calcium, Zinc, Magnesium) - 5',
                    'Liver Function Extended (LFT) - 12 Parameters',
                    'Kidney Function & Cystatin-C - 8 Parameters',
                    'Complete Hemogram 6-Part DIFF - 28 Parameters',
                    'Complete Urine Profile - 24 Parameters',
                    'Free Pathology Doctor Consultation on Report',
                ],
                'original_price' => 7999.00,
                'discounted_price' => 3999.00,
                'discount_percent' => 50,
                'fasting_required' => true,
                'sample_type' => 'Blood & Urine',
                'report_time' => 'Within 24-36 Hours',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Jaanch Diabetic Profile – Basic',
                'slug' => 'jaanch-diabetic-profile-basic',
                'category' => 'diabetes',
                'category_label' => 'Diabetes Care',
                'badge' => 'Essential Care',
                'test_count' => 5,
                'short_description' => 'Measure, Manage, Master. Essential glycemic screening to detect early prediabetes or monitor existing insulin regulation.',
                'parameters' => [
                    'HbA1c (Glycated Hemoglobin) - Gold Standard',
                    'Average Blood Glucose (eAG)',
                    'Fasting Blood Sugar (FBS)',
                    'Serum Creatinine (Kidney Protection)',
                    'Urine Glucose & Ketone Screen',
                ],
                'original_price' => 950.00,
                'discounted_price' => 499.00,
                'discount_percent' => 47,
                'fasting_required' => true,
                'sample_type' => 'Blood',
                'report_time' => 'Same Day (Within 6 hrs)',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Jaanch Diabetic Advanced Panel',
                'slug' => 'jaanch-diabetic-profile-advanced',
                'category' => 'diabetes',
                'category_label' => 'Diabetes Care',
                'badge' => 'In-Depth',
                'test_count' => 15,
                'short_description' => 'Comprehensive diabetes evaluation assessing cardiac risks, kidney microalbumin, insulin resistance, and blood sugar control.',
                'parameters' => [
                    'HbA1c (Glycosylated Hemoglobin)',
                    'Fasting Blood Glucose & Fasting Serum Insulin (HOMA-IR)',
                    'Complete Lipid Profile (10 Parameters)',
                    'Urine Microalbumin to Creatinine Ratio (UACR)',
                    'Serum Urea, Creatinine & eGFR',
                ],
                'original_price' => 1900.00,
                'discounted_price' => 999.00,
                'discount_percent' => 47,
                'fasting_required' => true,
                'sample_type' => 'Blood & Urine',
                'report_time' => 'Same Day (Within 8 hrs)',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Liver Function Tests Extended (LFT)',
                'slug' => 'liver-function-test-in-guwhati',
                'category' => 'liver',
                'category_label' => 'Vital Organs',
                'badge' => 'Specialist Rated',
                'test_count' => 12,
                'short_description' => 'Measure, Monitor & Maintain. Identifies fatty liver changes, enzyme elevation, jaundice, and cellular liver health.',
                'parameters' => [
                    'Bilirubin Total',
                    'Bilirubin Direct (Conjugated)',
                    'Bilirubin Indirect (Unconjugated)',
                    'SGOT / AST (Aspartate Aminotransferase)',
                    'SGPT / ALT (Alanine Aminotransferase)',
                    'Alkaline Phosphatase (ALP)',
                    'Gamma-Glutamyl Transferase (GGT)',
                    'Total Serum Protein',
                    'Serum Albumin',
                    'Serum Globulin',
                    'Albumin / Globulin Ratio (A:G)',
                    'SGOT / SGPT Ratio',
                ],
                'original_price' => 1200.00,
                'discounted_price' => 599.00,
                'discount_percent' => 50,
                'fasting_required' => true,
                'sample_type' => 'Blood Serum',
                'report_time' => 'Same Day (Within 6 hrs)',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Renal Care / KIDPRO (Kidney Function Profile)',
                'slug' => 'kidpro-kidney-profile',
                'category' => 'kidney',
                'category_label' => 'Vital Organs',
                'badge' => 'Renal Health',
                'test_count' => 7,
                'short_description' => 'Streamline your health journey with renal care. Evaluates filtration efficiency, waste clearance, and electrolyte balance.',
                'parameters' => [
                    'Serum Creatinine',
                    'Blood Urea',
                    'Blood Urea Nitrogen (BUN)',
                    'Uric Acid',
                    'Serum Calcium',
                    'Serum Phosphorus',
                    'BUN / Creatinine Ratio',
                ],
                'original_price' => 990.00,
                'discounted_price' => 499.00,
                'discount_percent' => 50,
                'fasting_required' => false,
                'sample_type' => 'Blood Serum',
                'report_time' => 'Same Day (Within 6 hrs)',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Heart Care & Lipid Profile Advanced',
                'slug' => 'lipid-profile-heart-care',
                'category' => 'cardiac',
                'category_label' => 'Heart Health',
                'badge' => 'Cardio Care',
                'test_count' => 10,
                'short_description' => 'Health checkup tells your inside story. Measure coronary risk, good & bad cholesterol, and atherogenic index.',
                'parameters' => [
                    'Total Cholesterol',
                    'HDL Good Cholesterol',
                    'LDL Bad Cholesterol',
                    'Triglycerides',
                    'VLDL Cholesterol',
                    'Non-HDL Cholesterol',
                    'Cholesterol / HDL Ratio',
                    'LDL / HDL Ratio',
                    'HDL / LDL Ratio',
                    'Triglycerides / HDL Ratio',
                ],
                'original_price' => 1300.00,
                'discounted_price' => 650.00,
                'discount_percent' => 50,
                'fasting_required' => true,
                'sample_type' => 'Blood Serum',
                'report_time' => 'Same Day (Within 6 hrs)',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Thyroid Care & Hormonal Balance (UTSH-LH-FSH-PRL)',
                'slug' => 'utsh-lh-fsh-prl-hormonal-profile',
                'category' => 'thyroid',
                'category_label' => 'Hormones',
                'badge' => 'Women & Hormones',
                'test_count' => 6,
                'short_description' => 'Feeling off lately? Weight changes, fatigue, or mood swings may relate to endocrine imbalance. High sensitivity analysis.',
                'parameters' => [
                    'Ultrasensitive TSH (UTSH)',
                    'Total Triiodothyronine (T3)',
                    'Total Thyroxine (T4)',
                    'Luteinizing Hormone (LH)',
                    'Follicle Stimulating Hormone (FSH)',
                    'Prolactin (PRL)',
                ],
                'original_price' => 1400.00,
                'discounted_price' => 699.00,
                'discount_percent' => 50,
                'fasting_required' => false,
                'sample_type' => 'Blood Serum',
                'report_time' => 'Same Day (Within 8 hrs)',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => '25-OH Vitamin D Total & Vitamin B12 Duo',
                'slug' => 'vitamin-d3-and-b12-duo',
                'category' => 'vitamins',
                'category_label' => 'Nutrition & Energy',
                'badge' => 'Immunity & Energy',
                'test_count' => 2,
                'short_description' => 'Your daily nutrition insights. Combat chronic fatigue, joint pain, muscle weakness, and numbness with precise serum vitamin levels.',
                'parameters' => [
                    '25-Hydroxy Vitamin D (Total D2 + D3)',
                    'Vitamin B12 (Cyanocobalamin)',
                ],
                'original_price' => 1800.00,
                'discounted_price' => 899.00,
                'discount_percent' => 50,
                'fasting_required' => false,
                'sample_type' => 'Blood Serum',
                'report_time' => 'Same Day (Within 8 hrs)',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Monsoon Fever Panel – Basic',
                'slug' => 'monsoon-fever-panel-basic',
                'category' => 'fever',
                'category_label' => 'Fever & Infection',
                'badge' => 'Rapid Diagnosis',
                'test_count' => 32,
                'short_description' => 'Rainy season is enjoyable, but your health matters too. Detect fever causes early: Malaria, Dengue, Typhoid & complete blood counts.',
                'parameters' => [
                    'Dengue NS1 Antigen Rapid',
                    'Malarial Antigen (Plasmodium Vivax & Falciparum)',
                    'Widal Slide Test (Typhoid Fever)',
                    'Complete Hemogram 6-Part DIFF (CBC - 28 Parameters)',
                    'Complete Urine Routine Examination',
                ],
                'original_price' => 1600.00,
                'discounted_price' => 799.00,
                'discount_percent' => 50,
                'fasting_required' => false,
                'sample_type' => 'Blood & Urine',
                'report_time' => 'Express (Within 4-6 hrs)',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 14,
            ],
        ];

        foreach ($packages as $pkg) {
            MedicalPackage::updateOrCreate(
                ['slug' => $pkg['slug']],
                $pkg
            );
        }
    }
}
